### ISSUE TITLE
Given When Then

### ISSUE THREAD

**Issue by hokrc01** [hirezio/vscode-testing-snippets#1]
Thanks for this library.  

It seems to me that it might be better to combine the "given when then" int one gwt short cut.
So I created the following snippet 

	"GIVEN WHEN THEN function":{
		"scope": "typescript, javascript",
		"prefix": ["gwt"],
		"body":["${1|Given,When,Then|}(() => {",
			"  $2",
			"});"],
		"description": "Given When Then"
	}

**Comment by shairez** [comment]
Thanks! 
Do you want to create a PR for it?

you can add it to the [Javascript snippets](https://github.com/hirezio/vscode-testing-snippets/blob/master/snippets/snippets-js.json)

**Comment by hokrc01** [comment]
Not really sure how to do it in this case.   But I would love to try

**Comment by shairez** [comment]
Awesome!

Please follow this guide - 

https://github.com/hirezio/vscode-testing-snippets/blob/master/CONTRIBUTING.md

and let me know if you need any help along the way or if something isn't clear there and needs more clarification.

Thanks!
